  ContentStyle:
    enabled: true
    addendum: "Questions? Contact #product-content on Slack or @Shopify/product-content on GitHub."
    rule_set:

      - violation: 'application'
        suggestion: 'app'

# This regex matches cases of "App" only when it doesn't begin a string or sentence.
      - violation: '(?:^.)((?![\.\!\?] App).)*App'    
        suggestion: 'app'
        violation_condensed: 'App'

      - violation: 'Lite Shopify Plan'
        case_insensitive: 'true'
        suggestion: 'Lite Shopify'

      - violation: 'Basic Shopify Plan'
        case_insensitive: 'true'
        suggestion: 'Basic Shopify'

      - violation: 
          - 'Professional Shopify Plan'
          - 'Professional Plan'
          - 'Pro Shopify Plan'
          - 'Pro Plan'
        case_insensitive: 'true'
        suggestion: 'Shopify'

      - violation: 'shopify'
        suggestion: 'Shopify'

      - violation: 
          - 'Unlimited Shopify Plan'
          - 'Unlimited Shopify Plan'
          - 'Unlimited Plan'  
        case_insensitive: 'true'
        suggestion: 'Advanced Shopify'

      - violation: 
          - 'Dashboard'
          - 'Shopify Dashboard'
        case_insensitive: 'true'  
        suggestion: 'dashboard' 

      - violation: 'discount number'     
        suggestion: 'discount code'
        case_insensitive: 'true' 

      - violation: 
          - 'dropdown'
          - 'drop down'
        case_insensitive: 'true'
        suggestion: 'drop-down'

      - violation: 
          - 'drop shipping'
          - 'drop-shipping'
        case_insensitive: 'true'
        suggestion: 'dropshipping'

      - violation: 
          - 'e-commerce'
          - 'E-commerce'
          - 'Ecommerce'
        suggestion: 'ecommerce'

      - violation:
          - 'e-mail'
          - 'email address'
        case_insensitive: 'true'
        suggestion: 'email'

      - violation: 
          - 'Internet'
          - 'Web'
          - 'web'
        suggestion: 'internet'

      - violation: 'line item'
        suggestion: 'item' 

      - violation: Link

- violation: 'hyperlink'
- violation: 'hyper-link'
    suggestion: 'link'

- violation: 'liquid'
    suggestion: 'Liquid'

- violation: 'main theme'
- violation: 'current theme'
- violation: 'active theme'
    suggestion: 'published theme'

- violation: 'Responsive Checkout'
- violation: 'Shopify Responsive Checkout'
    suggestion: 'responsive checkout'

- violation: 'POS store'
- violation: 'Retail store'
    suggestion: 'retail store'

- violation: 'Shopify Gurus'
- violation: 'gurus'
    suggestion: 'Shopify Support'



- violation: 'Shopify Help Staff'
- violation: 'Shopify call center'
    suggestion: 'Shopify Support'

- violation: 'Shopify home'
    suggestion: 'Shopify Home'

- violation: 'Shopify partners'
    suggestion: 'Shopify Partners'

- violation: 'Shopify payments'
- violation: 'payments'
    suggestion: 'Shopify Payments'

- violation: 'Shopify point of sale'
- violation: 'Shopify point-of-sale'
- violation: 'Shopify Point-of-Sale'
    suggestion: 'Shopify POS'

- violation: 'Shopify Plus clients'
- violation: 'Shopify plus customers'
     suggestion: 'Shopify Plus merchants'

- violation: 'Shopify shipping'
    suggestion: 'Shopify Shipping'

- violation: 'Template'
    suggestion: 'template'

- violation: 'Theme'
    suggestion: 'theme'

- violation: 'third party'
- violation: '3rd party'
    suggestion: 'third-party'

      - violation: 'toolbar'
- violation: 'meta nav'
    suggestion: 'top bar'

      - violation: 'transition'
- violation: 'rotation style'
  suggestion: 'transition effect'

- violation: 'trash-can button'
- violation: 'dustbin icon'
- violation: 'garbage'
- violation: 'delete button'
    suggestion: 'trash button'
   
-violation: '[Bb]uy button'
   suggestion:  'Buy Button'

-violation: 'Shopify [Bb]uy button'
   suggestion:  'Shopify Buy Button'

-violation: 'cancelled'
   suggestion:  'canceled'
-violation: 'cancelling'
   suggestion:  'canceling'
-violation: 'cancelation'
   suggestion:  'cancellation'

-violation: 'carrier calculated shipping'
   suggestion:  'carrier-calculated shipping'

-violation: 'cart'
   suggestion:  'cart page'

-violation: 'Handle'
   suggestion:  'handle'

-violation: 'Hardware'
-violation: 'Shopify Hardware'
   suggestion:  'hardware'

-violation: 'info'
   suggestion:  'information'

-violation: 'customers'
-violation: 'clients
-violation: 'shop owners'
-violation: 'store-owners'
-violation: 'store owners''
   suggestion:  'merchants'

-violation: 'On-Demand Deliveries'
-violation: 'Same-day deliveries'
-violation: 'local deliveries'
   suggestion:  'on-demand deliveries'

-violation: 'online store'
-violation: 'ecommerce store'
   suggestion:  'Online Store'

-violation: 'Payment Gateway'
-violation: 'payment-gateway'
   suggestion:  'payment gateway'

-violation: 'Admin'
-violation: 'Shopify Admin'
-violation: 'store's [Aa]dmin'
-violation: 'backend store Admin'
   suggestion:  'Shopify admin'

-violation: 'Shopify experts'
   suggestion:  'Shopify Experts'

-violation: '[Mm]anual'
-violation: 'Shopify [Mm]anual'
-violation: 'Docs'
-violation: 'documentation'
-violation: 'Support Docs'
-violation: 'Shopify help center'
   suggestion:  'Shopify Help Center'

-violation: '^((?!Shopify Help Center).)*[Hh]elp [Cc]enter'
   suggestion:  'Shopify Help Center'
   violation_condensed: 'help center'

-violation: 'theme store'
   suggestion:  'Shopify theme store'

-violation: 'display'
   suggestion:  'show'

-violation: 'side bar'
   suggestion:  'sidebar'

-violation: 'product with only one variant'
   suggestion:  'single-variant product'

-violation: 'social sharing'
-violation: 'social'
   suggestion:  'social media'

-violation: 'social media buttons'
   suggestion:  'social media icons'

-violation: 'staffmember'
-violation: 'staff'
   suggestion:  'staff member'

-violation: '[Ss]hop'
-violation: 'Store'
-violation: 'storefront'
   suggestion:  'store'

-violation: 'other themes'
-violation: 'inactive theme'
-violation: 'alternative theme'
   suggestion:  'unpublished theme'

-violation: 'url'
-violation: 'web address'
   suggestion:  'URL'

-violation: 'Variant Image(s)'
   suggestion:  'variant image(s)'
   
-violation: 'web page'
   suggestion:  'webpage'

-violation: '[Ww]eb [Ss]ite'
   suggestion:  'website'

-violation: '[Ww]ifi'
-violation: 'Wi-Fi'
   suggestion:  'wi-fi'

Internal Facing

-violation: 'ALT text'
-violation: 'alt image text'
-violation: 'ALT image text'
-violation: 'alternative image text'
   suggestion:  'alt text'

-violation: 'below footer'
-violation: 'sub-footer'
   suggestion:  'bottom bar'

-violation: 'development shops'
-violation: 'dev shops'
   suggestion:  'development stores'

-violation: 'sub-heading'
   suggestion:  'subheading'

Existing rules in Rorybot
-violation: 'lite plan''
   suggestion:  'Lite plan''

-violation: 'unlimited plan'
   suggestion:  'Unlimited plan'

-violation: 'shopify point of sale'
   suggestion:  'Shopify POS'

-violation: 'shopify manual'
   suggestion:  'Shopify Help Center'

-violation: 'shopify docs'
   suggestion:  'Shopify Help Center'

-violation: 'the documentation'
   suggestion:  'Shopify Help Center'

-violation: 'support docs'
   suggestion:  'Shopify Help Center'

-violation: 'help centre'
   suggestion:  'Shopify Help Center'

-violation: 'unfortunately'
-violation: 'sorry'
-violation: 'oops'
-violation: 'uh oh'
  Suggestion: Be direct instead of apologetic

-violation: 'shopify administrative panel'
-violation: 'shopify dashboard'
  suggestion:  'Shopify admin'

-violation: 'e.g.'
-violation: 'eg.'
-violation: 'eg'
  suggestion:  'like', 'for example'

-violation: 'ie'
-violation: 'i.e.'
-violation: 'ie.'
  suggestion:  'that is'

-violation: 'via'
  suggestion: avoid Latin abbreviations

-violation: 'off of'
-violation: 'open up
-violation: 'close down'
  suggestion:  'Avoid unnecessary prepositions.'

-violation: 'as of yet'
-violation: 'open up
-violation: 'close down'
  suggestion:  'Avoid unnecessary prepositions.'

-Violation: 'type in'
-Violation: 'due to the fact'
  Suggestion: 'Avoid unnecessarily wordy phrases.'




-violation: 'customise'
  suggestion:  'customize'

-violation: 'centre'
  suggestion:  'center'

-Violation: 'click on'
  Suggestion: 'click'

-Violation: 'would like to'
  Suggestion: 'want to'

-Violation: 'wish to'
  Suggestion: 'would like to'

-Violation: 'once the'
    Suggestion: 'when' or 'after'
   
-Violation:  "once you": {
    Suggestion: 'when' or 'after'
    
-Violation: 'may'
    Suggestion: 'might'
 

 





